version: '3'
services:
  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: phoenix
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
